/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 06-juil.-2026 17:20:16 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Annonce` CASCADE
;

DROP TABLE IF EXISTS `EtatAnnonce` CASCADE
;

DROP TABLE IF EXISTS `EtatGeneral` CASCADE
;

/* Create Tables */

CREATE TABLE `Annonce`
(
	`NumAnnonce` INT NOT NULL,
	`NumCompte` INT NULL,
	`NumCat` INT NULL,
	`NumArticle` INT NULL,
	`Titre` VARCHAR(255) NULL,
	`Soustitre` VARCHAR(255) NULL,
	`DatePublication` DATETIME NULL,
	`Quantite` MEDIUMINT NULL,
	`PrixDepart` FLOAT NULL,
	`PrixFixe` FLOAT NULL,
	`PrixDeReserve` FLOAT NULL,
	`PrixOffreSecondeChance` FLOAT NULL,
	`SKU` VARCHAR(255) NULL,
	`SKUFamille` VARCHAR(255) NULL,
	`ISBN` VARCHAR(255) NULL,
	`ASIN` VARCHAR(255) NULL,
	`UPC` VARCHAR(255) NULL,
	`EAN` VARCHAR(255) NULL,
	`MPN` VARCHAR(255) NULL,
	`Marque` VARCHAR(255) NULL,
	`NumEtatGeneral` SMALLINT NULL,
	`NumCaracteristique` INT NULL,
	`Image1` VARCHAR(255) NULL,
	`Image2` VARCHAR(255) NULL,
	`Image3` VARCHAR(255) NULL,
	`Image4` VARCHAR(255) NULL,
	`Image5` VARCHAR(255) NULL,
	`Image6` VARCHAR(255) NULL,
	`NumEtat` SMALLINT NULL,
	CONSTRAINT `PK_Annonce` PRIMARY KEY (`NumAnnonce` ASC)
)

;

CREATE TABLE `EtatAnnonce`
(
	`NumEtat` SMALLINT NOT NULL,
	`LibelleFr` VARCHAR(100) NULL,
	`LibelleEn` VARCHAR(100) NULL,
	CONSTRAINT `PK_EtatAnnonce` PRIMARY KEY (`NumEtat` ASC)
)

;

CREATE TABLE `EtatGeneral`
(
	`NumEtat` SMALLINT NOT NULL,
	`LibelleFr` VARCHAR(100) NULL,
	`LibelleEn` VARCHAR(100) NULL,
	CONSTRAINT `PK_EtatGeneral` PRIMARY KEY (`NumEtat` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Annonce` 
 ADD CONSTRAINT `FK_Annonce_EtatAnnonce`
	FOREIGN KEY (`NumEtat`) REFERENCES `EtatAnnonce` (`NumEtat`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Annonce` 
 ADD CONSTRAINT `FK_Annonce_EtatGeneral`
	FOREIGN KEY (`NumEtatGeneral`) REFERENCES `EtatGeneral` (`NumEtat`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;
